### ISSUE TITLE
Tableau supported npm package

### ISSUE THREAD

**Issue by andre347** [tableau/embedding-api-v3-guide#1]
Will there be an official Tableau supported npm package for v3?

**Comment by Kovner** [comment]
Yes this is a goal. We are still working out whether we'll be able to get it done in the initial release, though.

**Comment by kopecmi8** [comment]
Any news about this? The current way how we can use your library is just bad.

**Comment by ewaldhofman-tableau** [comment]
I am sorry, but we have not prioritized this yet.

**Comment by bcantoni** [comment]
This is available now: https://help.tableau.com/current/api/embedding_api/en-us/docs/embedding_api_get.html#installing-the-npm-package
