### ISSUE TITLE
Unable to initialize a Viz via JavaScript

### ISSUE THREAD

**Issue by florent-guinard** [tableau/embedding-api-v3-guide#12]
Hi,

We're unable to initialize a Viz via the "JavaScript" method:

The following code
`import {TableauViz} from './tableau-3.0.0.js';
let viz = new TableauViz();`
produces this error:
> Uncaught SyntaxError: The requested module './tableau-3.0.0.js' does not provide an export named 'TableauViz'

if we switch the import to:
`import * as tableauApi from './tableau-3.0.0.js';`
we end up with this error:
![image (3)](https://user-images.githubusercontent.com/93193181/138860051-0dd704c5-cd66-49be-86ad-32d1aa3435d0.png)

Initializing the Viz using the `<tableau-viz>` HTML component works properly.

We're using the JS API available at https://embedding.tableauusercontent.com/dist-embedding/tableau.embedding.3.0.latest.beta.js

**Comment by ashwinar** [comment]
The ability to initialize via javascript is currently in the works. We will enable that functionality in our next update to the library.

**Comment by wattsin** [comment]
Is this still the case? I am using https://embedding.tableauusercontent.com/tableau.embedding.3.0.0.min.js and I am getting the same issue.

**Comment by illonage** [comment]
@wattsin Yes, it is going to be part of Embedding v3.1 pre-release. Sign up for the developer program: developer.tableau.com to be the first one to know about the pre-release

**Comment by illonage** [comment]
Hi @wattsin & @florent-guinard,

Great news, Tableau Embedding API v3.1 is developer preview. Our documentation is available [here](https://embedding.tableauusercontent.com/preview/getting-started-v3.html)

Let us know what you think!

**Comment by wattsin** [comment]
> 

Yeah awesome, I did try this. But it did not function with my server version. I need to use the x10 instance(not sure on the name) which is the latest preview version that works with 3.1. I recommend adding some functionality to 3.X to check the version and die if its not compatible. It would have saved me hours

**Comment by florent-guinard** [comment]
@illonage Thanks, we'll check that asap !

**Comment by ZarrocIndustrious** [comment]
how could I initialize this inside of a react app.
