### ISSUE TITLE
no embedding api v3 in javascripts/api/ of the Tableau Server

### ISSUE THREAD

**Issue by mayakostova** [tableau/embedding-api-v3-guide#13]
Hi, 

I can't seem to find the file described in the ReadMe as the v3 of the Embeding API. We are using tableau sever 2020.3. In which version is the new API available?

**Comment by illonage** [comment]
Hi @mayakostova,

Thank you for your interest. 

The Embedding API v3 is currently in Developer Preview, you can find our Getting Started Guide [here](https://embedding.tableauusercontent.com/docs-embedding/getting-started-v3.html).

You can test it using your Developer Sandbox Site that you can request for free once you join the [Developer Program](https://www.tableau.com/developer).

Let us know if you have any feedback,
Gigi

**Comment by illonage** [comment]
Let us know if you have additional question, but I will go ahead and close this issue
