### ISSUE TITLE
Not Implemented Error -- What does this mean? 

### ISSUE THREAD

**Issue by kbrown-blend360** [tableau/embedding-api-v3-guide#15]
Trying to use export functions to export via the new V3 embed. Viz loads fine, and I can access the element. Keep running into a "not-implemented: Not implemented" error. 

Documentation literally says nothing about this error:
https://help.tableau.com/current/api/embedding_api/en-us/reference/enums/embeddingerrorcodes.html#notimplemented

Looking that the V3 source code (3.0.0.js), it looks like a FAIR amount of viz methods are just going to throw an error regardless: 

    pauseAutomaticUpdatesAsync() {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }

    resumeAutomaticUpdatesAsync() {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }

    toggleAutomaticUpdatesAsync() {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }

    revertAllAsync() {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }

    refreshDataAsync() {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }

    showDownloadWorkbookDialog() {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }
    showExportImageDialog() {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }
    showExportPDFDialog() {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    showExportDataDialog(worksheetInDashboard) {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    showExportCrossTabDialog(worksheetInDashboard) {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }
    showShareDialog() {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }
    getCurrentSrcAsync() {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }
    redoAsync() {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }
    undoAsync() {
        throw new api_shared_js_1.TableauError(Contract.EmbeddingErrorCodes.NotImplemented, 'Not implemented');
    }
    
The documentation shows that these are all valid methods. What am I missing here?

**Comment by illonage** [comment]
Hi @kbrown-blend360 - The methods that are using are not implemented in the Embedding v3.0. Some of these methods are going to be available in the next release, Embedding v3.1 or some later in the year. To be informed of the new releases, you can join the Tableau Developer Program: developer.tableau.com
