### ISSUE TITLE
Dispose functionality

### ISSUE THREAD

**Issue by wattsin** [tableau/embedding-api-v3-guide#17]
Right now, I can't initialize the viz with JS. So its a <tableau-viz> element, I would like to be able to dispose of the viz and load a new one. It seems to work without the dispose, but I can't apply filters once it's recreated.

I use jquery .load to add the <tableau-viz> to the DOM which works fine. I then can add event listeners etc.  If I do a second .load overwriting the first <tableau-viz> the dashboard will load with the event listeners but I can't apply filters to this new object.

The old way:

https://help.tableau.com/current/api/js_api/en-us/JavaScriptAPI/js_api_sample_dynamic_load.htm

**Comment by retwedt** [comment]
I'm running into this same issue, did you end up finding a resolution?

**Comment by wattsin** [comment]
> I'm running into this same issue, did you end up finding a resolution?

3.0 has some issues, I had a few issues trying to work with the dashboard programmatically. I had to ditch any interaction, I've switched to setting the src when I wanted to change of the dashboard, when I want to change the filters I add them as html elements and refresh the src. Its not pretty but it works until 3.1 comes out.

**Comment by illonage** [comment]
Hi @wattsin - Did you try v3.1 already? Can you confirm that the issues you saw are fixed in 3.1?

**Comment by wattsin** [comment]
> Hi @wattsin - Did you try v3.1 already? Can you confirm that the issues you saw are fixed in 3.1?

No I have not, I needed a solution to work with the current version of tableau server not the preview. I will test it when its released
