### ISSUE TITLE
What is the <tableau-viz> property for FirstInteractive?

### ISSUE THREAD

**Issue by kbrown-blend360** [tableau/embedding-api-v3-guide#18]
There is an example in the guide that shows we can add event listeners directly to the <tableau-viz> element via properties:

```
<tableau-viz id="tableauViz" 
      src="http://my-server/views/my-workbook/my-view"
      onMarksSelected="handleMarksSelection">
</tableau-viz>
```

Two questions:
1) Is this functionality working? I see no where in the source code where "onMarksSelected" exists, so that's why I ask.
2) What is (or will be) the equivalent of "FirstInteractive"?

**Comment by illonage** [comment]
Hi @kbrown-blend360 

Thank you for opening this issue.

1. This functionality is not working today but should be available in the upcoming releases (v3.2 or v3.3)
2. [Here](https://glitch.com/~eapi-firstinteractive) an example for "FirstInteractive":

**Comment by jontom33** [comment]
Is there a way with the "embedding api v3" to include FirstInteractive functions after the viz is initialized?  or do we have to wait until v3.2 or v3.3 comes out?   We are looking to use connected apps but without this functionality we can't proceed.

**Comment by illonage** [comment]
Hi @jontom33 - You can add event listeners such as FirstInteractive after initialization in v3.0: https://help.tableau.com/current/api/embedding_api/en-us/docs/embedding_api_event.html
