### ISSUE TITLE
Applying filters after reloading `tableau-viz` element

### ISSUE THREAD

**Issue by retwedt** [tableau/embedding-api-v3-guide#25]
I have an app with multiple pages, and one of them is a Tableau Embedded View that uses the `tableau-viz` element.

The first time I load the page with the `tableau-viz` element, I can apply filters using the `applyFilterAsync` method.  If I leave the Tableau View page to visit another page in the app, and then return to the Tableau View page, `applyFilterAsync` no longer works.

The `tableau-viz` element is being removed/added to the DOM when I navigate away/to the Tableau View page.

Is there a way to `dispose` of the Viz object?  I don't see the method in the documentation for v3, those this was possible in v2.

**Comment by illonage** [comment]
Hi @retwedt - Thank you for opening this issue. To be able to investigate further, can you share how 'tableau-viz' is being added/removed to the DOM please?

**Comment by illonage** [comment]
Not having a `dispose()` method in v3 was intentional. Adding and removing `tableau-viz` from DOM  & creating viz programmatically was the intention behind dynamic loading of vizzes in v3

**Comment by retwedt** [comment]
Hey @illonage thanks for the quick reply!

I am working on a React app, which uses React Router.  I run into the issue when I start on the page with the Tableau Viz, navigate to another page within the app, and then return to the Tableau Viz page.

This is effectively removing the element from the DOM, though I am not doing it explicitly using the `document`.

**Comment by illonage** [comment]
@retwedt do you mind sharing ur code where you add or remove `tableau-viz` please?
- If you remove the TableauViz element from dom and then try to append the same object back, the Viz will not load.
- If you remove the TableauViz element from dom and then try to append a new tableau Viz object to the dom, the Viz will load; and the applyFilterAsync api should work as expected.

**Comment by retwedt** [comment]
@illonage Unfortunately it is a private repository.  I will try to put together a demo that shows the issue I am running into.

**Comment by illonage** [comment]
@retwedt did you solve this issue?

**Comment by retwedt** [comment]
We were able to figure out a workaround, using controls within the embedded dashboard as opposed to external controls using the JS SDK.
Thanks for your assistance!
