### ISSUE TITLE
Precision of float values from the summary data different from the JavaScript API

### ISSUE THREAD

**Issue by florent-guinard** [tableau/embedding-api-v3-guide#28]
The precision of float values returned by the [Worsksheet.getSummaryDataAsync](https://embedding.tableauusercontent.com/preview/interfaces/worksheet.html#getsummarydataasync) function has changed between the Javascript API and the Embedding API.

We have a basic Worksheet embedded with both APIs and we log its summary data using the same code:
`const sheet = viz.workbook.activeSheet;`
`const data = await sheet.getSummaryDataAsync();`
`console.log(data);`

For the same data point, in the Javascript API:
![image](https://user-images.githubusercontent.com/93193181/173867114-e64552f6-0c34-4f94-ac3e-b0a13d896f21.png)
in the Embedding API:
![image](https://user-images.githubusercontent.com/93193181/173866885-57cd4aad-16d9-4f95-819a-8cfaa1dc622a.png)

**Comment by illonage** [comment]
Hi Florent - Yes, we are aware of it. Do you need this level of precision? Right now, we are not planning to address it but let us know if it is blocking issue

**Comment by florent-guinard** [comment]
@illonage Thanks for your feedback. The only issue we have with this change (the level of precision doesn't matter in our case) is the difference of behaviour between the Javascript and the Embedding API: if we compare the data of a Worksheet on a 2022.1 site (using the Javascript API) wiith the exact same Worksheet on a 2022.2 site (using the Embedding API) we'll have differences due to this level of precision even though the underyling data is absolutely identical.
It's not a blocking issue though, we should be able to find a solution in this specific case.
