### ISSUE TITLE
Incorrect float parameter value

### ISSUE THREAD

**Issue by florent-guinard** [tableau/embedding-api-v3-guide#29]
I have an issue with the Embedding API retrieving the value of a float parameter in one of our Worksheets:
![image](https://user-images.githubusercontent.com/93193181/173867835-aabd7893-2705-4659-99d6-b91a15477021.png)

This Worksheet is embedded with the Embedding API and we use the following code to logs its parameters:
`const sheet = viz.workbook.activeSheet;`
`const parameters = await viz.workbook.getParametersAsync();`
`console.log(parameters);`

The Embedding API returns an incorrect value for this parameter:
![image](https://user-images.githubusercontent.com/93193181/173868256-cb3fc3b4-20e5-4995-a878-ade18f2d6d6e.png)

The JavaScript API returns the expected value for the same Worksheet/parameter:
![image](https://user-images.githubusercontent.com/93193181/173868413-4eca791b-8d0f-40b7-b062-b9c6aaf63a55.png)

**Comment by illonage** [comment]
Hi @florent-guinard - I am not able to reproduce it. Could you give me edit access to your workbook please?

**Comment by florent-guinard** [comment]
@illonage Sure: https://glitch.com/edit/#!/vanilla-pyrite-beret

**Comment by illonage** [comment]
@florent-guinard I would need edit access to the workbook to check how you set up your parameter
