### ISSUE TITLE
Permissions Retrieval for Toolbar Interactions

### ISSUE THREAD

**Issue by Mrkbingham** [tableau/embedding-api-v3-guide#3]
Will we be able to determine permissions for toolbar actions? 

A lot of people (myself included) extrapolate the toolbar UI elements into their application.  However determining what level of access people have through the REST API is very circuitous as permissions need to be checked against every level (project, workbook, view) and may not necessarily be user-specific.

In my opinion this would ideally be handled by the REST API*.  However, if that's not viable a quick call to determine the availability of certain functions would be fantastic.

*My REST API suggestion would be either to 
1) Add permission as an optional response included in the call: 
`GET /api/api-version/sites/site-id/users/user-id/workbooks`
or
2) Add a separate API endpoint for permission retrieval that resolves to the user in question rather than the object in question

**Comment by Kovner** [comment]
yeah this request makes sense and isn't something I've thought of before: If you are doing toolbar functionality in your embedded app, you want to know what the user has permissions for.
Why do you want this in the REST API rather than the JSAPI, though?

**Comment by Mrkbingham** [comment]
First, I should clarify - I mentioned toolbar permissions here, but that should probably just be expanded to all permissions on a viz: 
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/4382816/122570806-b7b44c00-d011-11eb-86f7-d853f9793398.png">

For the REST API, I figured architecturally it would be simpler to slightly modify the permissions calls from the REST API rather than build a net-new feature in the JS API.  Also from a performance perspective the REST API can be easily cached server-side on an app, or can also be called prior to onFirstInteractive() which speeds up some load time while the viz is loading. 

But if this were to go into the JS API, like viz.getPermissions() it would still definitely achieve the same goal, so definitely happy wherever it lands, but I'd have a slight preference on the REST API.
