### ISSUE TITLE
Expand TableauEventType

### ISSUE THREAD

**Issue by Nikita-Kolos** [tableau/embedding-api-v3-guide#33]
Please extend [TableauEventType](https://help.tableau.com/current/api/embedding_api/en-us/reference/enums/tableaueventtype.html)
We really miss old event types like:

1) tabswitch
2) parametervaluechange
3) storypointswitch
4) urlaction
5) vizresize

**Comment by illonage** [comment]
Hi @Nikita-Kolos - Thank you for opening this issue! We added these "old event types" in the Embedding API v3.3 that is now in developer preview: https://embedding.tableauusercontent.com/preview/getting-started-v3.html
