### ISSUE TITLE
How to apply filter for multiple worksheets in a dashboard

### ISSUE THREAD

**Issue by Shyam268** [tableau/embedding-api-v3-guide#37]
The tableau dashboard has a multiple worksheets (composite view). and all worksheets are filtered by same id. when i provide filter to dashboard it applies to only one worksheet. other filters are set to "None". and each worksheet has separate dropdown with same id's.

This is the code snippet

`
      <tableau-viz id="tableauViz"       
          src='server/views/workbook/workshhet'      
          token={JWT}
          toolbar='hidden'>
          <viz-filter  field="id" value="1de9ec86-xxxxx-4878-yyyy-609e55677ce2f"> </viz-filter>    
     </tableau-viz>
`
how to apply filters to other worksheets ?

**Comment by illonage** [comment]
Hey @Shyam268 - Thank for opening an issue. Are all your worksheets using the same data source? If you add a drop down filter to the dashboard and filter the data, does it work?

**Comment by Shyam268** [comment]
@illonage Yes all worksheets using same data source and drop down filter is working as expected. 
onLoad is not working. is there any event similar to onLoad ? .  need an event when dashboard loading is completed.

**Comment by Shyam268** [comment]
working for other dashboards.
