### ISSUE TITLE
Is it possible to embed AskData workbook using connected Apps ( Embedding API v3 ) ?

### ISSUE THREAD

**Issue by hackwithharsha** [tableau/embedding-api-v3-guide#41]
As of now, we are facing the following issue.

Ask Data isn't supported by this version of Tableau Server.. This issue happens only while embedding.

However, it works when I open the workbook in Tableau Server (On-Premise: 2022.1.3 )

**Comment by illonage** [comment]
Hi @hackwithharsha - Are you getting an error message? How are you embedding Ask Data?

**Comment by bcantoni** [comment]
The [Ask Data feature has been retired](https://help.tableau.com/current/pro/desktop/en-us/ask_data.htm), so we can close this one.
