### ISSUE TITLE
Worksheet.applyRangeFilterAsync function stopped throwing errors when the filterName is invalid

### ISSUE THREAD

**Issue by florent-guinard** [tableau/embedding-api-v3-guide#42]
Embedding API used: https://online.tableau.com/javascripts/api/tableau.embedding.3.latest.min.js
Tableau site used: 2022.4 Tableau Online preview site (10ax)

The [Worksheet.applyRangeFilterAsync](https://help.tableau.com/current/api/embedding_api/en-us/reference/interfaces/worksheet.html#applyrangefilterasync) function doesn't throw any error if the "filterName" doesn't match any existing filter in the opened Worksheet.

An error is properly thrown if we open a Worksheet from a 2022.3 Tableau Online site instead. This used to work a few weeks/days ago on the same Tableau Online site.

Reproduction code:
https://glitch.com/edit/#!/heathered-lofty-marquess

**Comment by anyoung-tableau** [comment]
This is fixed in v3.4 of the Embedding API which is rolling out with 22.4. The version of the Embedding API at https://online.tableau.com/javascripts/api/tableau.embedding.3.latest.min.js is still v3.3.
