### ISSUE TITLE
Having hook or some event to know the HTTP status of iFrame

### ISSUE THREAD

**Issue by hackwithharsha** [tableau/embedding-api-v3-guide#46]
### Issue 1

There should be some kind of event or hook to get the HTTP status code of API request that TableauViz component is sending.. currently, There is no way to get this information due to cross-origin policy of iFrame. As you already have ‘firstinteractive’ hook. Is it possible to add some event to get this status code information ?

### Issue 2

It’s okay for developers to see these black screens with error code. But, our customers or users don’t know what they mean.. Either you could provide some fallback component or HTML element or implement feedback 2.. so, developers can handle these error messages differently based on HTTP Status Code.

### Issue 3

We are using only single token to render both the visualizations. Sometimes, one of the visualization will throw “Sign in to Tableau Server”.. If it’s token issue, It should throw for both the visualizations right ? as it is a single session. This is an intermittent issue happen once in a while. Don’t know why it happens. Same here also, I want my customers or users to see this “Sign in to Tableau Server”… I would handle it differently if we would have “Feedback 2” implemented.

Following issues happen due to network issues or someother reason.. I don't want my production application users see this UI... If you provide status code or fallback component.. I would handle it differently.

![Feedback_2](https://user-images.githubusercontent.com/64857451/196930859-2ce7cc2f-7b78-44df-8e5b-034ab9a97547.png)

![Feedback_1](https://user-images.githubusercontent.com/64857451/196930887-5e4caab6-05c3-43f2-9a7a-e32c2570cb3b.png)

**Comment by bcantoni** [comment]
This should be resolved now that we made several auth error handling improvements last year (late 2023).
