### ISSUE TITLE
Be able to query for server admin rights

### ISSUE THREAD

**Issue by jstrauss18** [tableau/embedding-api-v3-guide#47]
Using the API methods, how do I find a list of server admin users?

The back story is that we're using the embedded API to render dashboards within our app, and before we attempt to render, we verify that the user is defined onto the site using method "GET /api/api-version/sites/site-id/users?filter=userid".  The problem with this is that some server admins have been testing the functionality and since they're not explicitly defined on the site (even though they have access to the dashboard), they get "you don't have access".  The workaround is to add them onto the site explicitly.

--------
The other thought is to add an inspectable return code from the embedding API that tells the app to display "you don't have access".

**Comment by bcantoni** [comment]
Closing due to age and it's more of a REST API question rather than Embedding.
