### ISSUE TITLE
Embed Metrics / Ask Data

### ISSUE THREAD

**Issue by Mrkbingham** [tableau/embedding-api-v3-guide#5]
Will this allow us to embed Metrics and/or Ask Data programmatically?

**Comment by Kovner** [comment]
[Ask Data can actually be embedded today](https://help.tableau.com/current/pro/desktop/en-us/ask_data_share.htm#embed-ask-data-in-a-web-page). Embeddable Metrics is also being worked on.

**Comment by Mrkbingham** [comment]
Ah yes, currently available with embed code.  I was referring to Ask Data being available to be embedded via the JS API programmatically to allow extensibility.  Being able to tap into APIs for those features could improve Tableau's platform advantage over competitors as well imo.

Both Metrics and Ask Data could benefit from parallel functionality as it relates to the current JS API.  For example Ask Data could benefit from use-cases where users may want to build a UI on top of the Ask Data embedded iFrame and export underlying data programmatically in the browser.

**Comment by illonage** [comment]
Hi @Mrkbingham, 

You can now embed [Ask Data via Embedding API ](https://www.tableau.com/products/new-features?utm_campaign_id=2017049&utm_campaign=Prospecting-ALL-ALL-ALL-ALL-ALL&utm_medium=Paid+Search&utm_source=Google+Search&utm_language=EN&utm_country=USCA&kw=&adgroup=CTX-Trial-Products-DSA&adused=DSA&matchtype=&placement=&d=7013y000000vYhH&gclid=Cj0KCQjwla-hBhD7ARIsAM9tQKtqXViX6bsyZHeNpilIK5tBYo8ri5fiXJRqoFlzIHbBKdFFyWDdrxoaAjqxEALw_wcB&gclsrc=aw.ds#item-96425) and [Metrics](https://help.tableau.com/current/pro/desktop/en-us/embed_metrics.htm)

Can we close this issue?

**Comment by Mrkbingham** [comment]
@illonage yep!
