### ISSUE TITLE
Getting an incorrect "range" value on a dashboard set to "automatic" sizing

### ISSUE THREAD

**Issue by Mrkbingham** [tableau/embedding-api-v3-guide#53]
I have set my dashboard sizing to automatic, but the embedding API is returning a range size:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/4382816/209396559-730a4f3d-73cc-4163-ac15-7e71b5312bb9.png">

This appears to happen on the `TableauEvent.FirstVizSizeKnown` event.  Once the onFirstInteractive has fired, the correct sizing details are coming back.

**Comment by illonage** [comment]
Hi Mark - Thank you for reporting this. To clarify, are you experiencing this only before onFirstInteractive is fired?

**Comment by bcantoni** [comment]
Closing due to age and no response on the last question.
