### ISSUE TITLE
When will Tableau no longer support Embedding API v2?

### ISSUE THREAD

**Issue by Juanitableau** [tableau/embedding-api-v3-guide#55]
I am aware that the support for JavaScript API v2 on Tableau will end soon but is it possible to provide any ideas of when Tableau will switch completely to Embedded API v3? This is because some users still want to stick with v2 until Tableau no longer accommodates it.

**Comment by ewaldhofman-sf** [comment]
@Juanitableau we are working on a plan, but haven't finalized on a end date yet. As soon as we know more, we will post an update.
