### ISSUE TITLE
Tableau not decoding URL encoding characters with Parameters & Filters 

### ISSUE THREAD

**Issue by hackwithharsha** [tableau/embedding-api-v3-guide#57]
```js
      const parameter_previous_end_date =  document.createElement('viz-parameter')
      parameter_previous_end_date.setAttribute('name', 'P.Previous_End_Date')
      parameter_previous_end_date.setAttribute(
        'value',
        '10/22/2023'
      )
      viz.appendChild(parameter_previous_end_date)
```

which will be added to the query param as https://baseurl.com&P.Previous_End_Date=10%2F22%2F2023

It looks like, Tableau is not decoding %2F URL characters on the server side, can you please confirm and consider it as bug,If it's real issue from your side or tell me alternate solution ?

**Comment by stephenlprice** [comment]
@hackwithharsha are you getting any errors when applying this parameter? What makes you think the issue is related to decoding these characters?

**Comment by hackwithharsha** [comment]
@stephenlprice I am not getting any errors.. Because remaining parameters where special character like / is not available is working perfectly fine...

and also when I change local to these tableau dashboards to India instead of UK where date format is dd-mm-yyyy, and then for the viz-parameter when i pass above format it's working fine...

The problem is when we choose date format as dd/mm/yyyy,,, where browser decodes / slash as %2F,

**Comment by hackwithharsha** [comment]
@stephenlprice  The issue could be something else also... As it is the server's responsibility to decode these URL-encoding characters.

For some reason, the initial date parameters are not working... Normal integer and string parameters are working perfectly fine

**Comment by hackwithharsha** [comment]
@stephenlprice  Issue is with the parameter date type. when I use string type, it is accepting - or /... 

Something else is happening, not sure why

**Comment by hackwithharsha** [comment]
String type is working for us... and then, we are using DATEPARSE function on tableau side to parse these string dates

**Comment by stephenlprice** [comment]
@hackwithharsha can you briefly describe how you solved this issue? I believe the cause was due to typing rather than decoding on our end

**Comment by hackwithharsha** [comment]
we were using date type parameter earlier... now, we changed it to string type parameter in tableau.. and then, in tableau we use DATEPARSE to parse the string values that embedding api is sending..
