### ISSUE TITLE
Invalid native values for [Measure Names] columns in Summary Data

### ISSUE THREAD

**Issue by florent-guinard** [tableau/embedding-api-v3-guide#60]
I have the following Worksheet:
![image](https://user-images.githubusercontent.com/93193181/227873122-257f5752-1810-4a66-99ba-c84e9b2df28a.png)

and I'm trying to retrieve its _summary data_:
![image](https://user-images.githubusercontent.com/93193181/227873763-e9eca097-3ff2-4759-b43b-994a1965cb17.png)
with the Embedding API.

Both the deprecated _getSummaryDataAsync_ and the _getSummaryDataReaderAsync_ functions are returning invalid data:
![image](https://user-images.githubusercontent.com/93193181/227874298-9ffc8618-8480-459b-8cda-5fe174c3dbe2.png)

Code to reproduce the issue:
https://glitch.com/edit/#!/linen-mercury-cinnamon

Workbook used:
[Workbook with Measure Values.zip](https://github.com/tableau/embedding-api-v3-guide/files/11075967/Workbook.with.Measure.Values.zip)

**Comment by ewaldhofman-sf** [comment]
@florent-guinard Could you please explain why the summary data is incorrect? 

I see exactly the same values as you see in the View Data window. What am I missing?

**Comment by florent-guinard** [comment]
@ewaldhofman-sf I apologize for this my original ticket isn't precise enough.
![image](https://user-images.githubusercontent.com/93193181/229059138-31ee583e-6cab-468b-82ee-f0da8f64a12c.png)

The _formatted value_ of the "Measure Names" column is correct (we get "Salary" for the first row) but the _value/native value_ information we get seems to be a reference to the measure instead of the expected "Salary" value.

In our use case we want to retrieve the Summary data unformatted to make sure that it contains the expected values, and for this specific Worksheet we end up with this "reference" instead of the "Salary/Age/..." values.

**Comment by ewaldhofman-sf** [comment]
@florent-guinard sorry for the late reply. It is kinda busy here with the preparations of TC. We have filed a defect with the number W-13040367. I will give you an update as soon as I can.

Thanks for reporting this, and taking the time to explain what went wrong.
Ewald

**Comment by ewaldhofman-sf** [comment]
Unfortunately, we have had to make the difficult decision to not fix this issue. Sorry for not having a better answer.
