### ISSUE TITLE
Summary Data of two Worksheets mixed up when included in a Dashboard

### ISSUE THREAD

**Issue by florent-guinard** [tableau/embedding-api-v3-guide#62]
We have a Workbook with two basic Worksheets:
![image](https://user-images.githubusercontent.com/93193181/231474100-83d141f7-6fa5-4566-a708-ab8638b51c2f.png)
![image](https://user-images.githubusercontent.com/93193181/231474182-e1366fc8-dfad-4dbe-a4d2-b90188d69b9e.png)
Those two Worksheets are included in a Dashboard:
![image](https://user-images.githubusercontent.com/93193181/231474367-d32045f9-e7e1-47f2-8014-f60c575105a0.png)

Each Worksheet has a single _mark_ in its Summary Data when we download the Dashboard data in the Tableau UI:
![image](https://user-images.githubusercontent.com/93193181/231475512-64035779-9c98-47bc-a0fe-ad3be647504e.png)
![image](https://user-images.githubusercontent.com/93193181/231475684-3f42a5fe-5955-4e35-a56b-ddd9f7b5b1fb.png)

Embedding this Dashboard with the latest version of the _Tableau Embedding API_ and using the` Worksheet.getSummaryDataAsync()` function doesn't return the expected results: two Worksheets are found but their Summary Data are somehow merged together:
![image](https://user-images.githubusercontent.com/93193181/231476756-dc3ebd9f-d390-4523-8f6a-8349c6c3b773.png)
![image](https://user-images.githubusercontent.com/93193181/231476908-1dda59b5-6720-4c34-bd6f-d6c23736600b.png)
Each Worksheet has two columns instead of one (they have the other Worksheet's column has well as their own), and thus two _marks_ instead of one.

The issue also happens when using the `Worksheet.getSummaryDataReaderAsync()` function.

Code to reproduce the issue:
https://glitch.com/edit/#!/puzzled-wirehaired-ship

I can't share the Workbook publicly but I'll gladly send it via email/Google Drive share.

**Comment by ewaldhofman-sf** [comment]
Thank you for reporting this @florent-guinard. I have been able to reproduce this issue: https://glitch.com/edit/#!/sordid-bejewled-plutonium

I filed a bug for this one with number W-13040486

Ewald

**Comment by bcantoni** [comment]
Looping back here, the internal bug which Ewald referenced was completed, so this issue should be fixed in Tableau Server 2024.1 and newer (including Tableau Cloud).
