### ISSUE TITLE
dub01 redirected you too many times error trying to display Embedded Vizs

### ISSUE THREAD

**Issue by florent-guinard** [tableau/embedding-api-v3-guide#64]
Since the 2023.2 on our **dub01 Tableau Cloud** site some users are no longer able to open Vizs embedded with the _Embedding API_ if a Connected App JWT is used, they are hit with a "dub01.online.tableau.com redirected you too many times" error:
![image](https://github.com/tableau/embedding-api-v3-guide/assets/93193181/dcab44c6-d728-4032-8abe-03e64fed2025)

- It happens for a specific set of users, other users with the exact same site role/authentication are able to open the same Vizs.
- It's not related to the authentication: affected users are using both "Tableau" and "Google" authentication
- The same users can open Vizs with Connected App JWTs in other **Tableau Cloud** sites
- Other users can open the same Vizs using the same Connected App
- The affected users have the same issue when they try to display embedded Vizs without a Connected App JWT

**Comment by ewaldhofman-sf** [comment]
Thanks for reporting this @florent-guinard. I have notified the team, and will get back to you when I know more.

**Comment by ewaldhofman-sf** [comment]
The team has a few questions:

1. Is it possible to get more information on exactly when this started happening and if the issue remains?  Perhaps after clearing cookies for the affected users?
2. Is it possible to grab a screenshot of the network tab when the viz is loading? (I'm interested to see which Connected Apps login API is being used)
3. Are there vizportal logs I can get?  (if this is a Tableau Cloud customer, knowing the pod and site would hlp)

If you are on the #DataDev slack workspace, you can also share the information there in private with me

**Comment by MirelaPo** [comment]
This is happening to us too on one of the sites. Tried reverting to version 3.5.0 and it is still happening. Cleared cookies, still a problem.


![chrome_3iaiSieSz7](https://github.com/tableau/embedding-api-v3-guide/assets/136869677/506b98ba-577e-47d4-9a4e-02233bd78aef)

**Comment by florent-guinard** [comment]
@ewaldhofman-sf I shared those information with you directly in Slack.

**Comment by VictorChirita** [comment]
so... what's the solution to the problem?

**Comment by florent-guinard** [comment]
> so... what's the solution to the problem?

@VictorChirita using a full lowercase site name in the Viz URL.
