### ISSUE TITLE
incompatible-version-error with embedding-api

### ISSUE THREAD

**Issue by brianshano** [tableau/embedding-api-v3-guide#72]
I'm getting an error using the `@tableau/embedding-api` library to embed a dashboard. 

I managed to also find a public one with the same issue and I'm sharing a codesandbox link so you can see it happening. 
https://codesandbox.io/p/devbox/tablo-dash-nty92j?file=%2Fapp%2Fdashboard%2FTableauMatching.tsx

Click the "Tablo dash" button to load it. 
You may see a hydration error which you can ignore.
It's using Next.js which handles the error and displays a red box in the corner which you can click to see it. 

`
Error: incompatible-version-error: The version of the Embedding library is not compatible with the version of Tableau. The visualization will load, but the Embedding API methods and events are not available.
`

**Comment by ewaldhofman-sf** [comment]
@brianshano have you validated that the location where you pull the embedding library from is the same as the location of the dashboard? And did you get the latest version of the library, or a specific one?

**Comment by brianshano** [comment]
Hi @ewaldhofman-sf 
The dashboard is in Tableau cloud and the embedding-api comes from npm. 

I did discover when trying different versions of the embedding-api, a certain version that matches our Tableau Cloud version was needed and worked without error. 

It worked when I set the package.json dependency to 
`"@tableau/embedding-api": "~3.8.0",`

**Comment by ewaldhofman-sf** [comment]
Great to hear that your issue is resolved. 

For future reference, you can find more information in the readme of the NPM package (first bullet): https://www.npmjs.com/package/@tableau/embedding-api
