### ISSUE TITLE
Create Data Alerts (No Toolbar)

### ISSUE THREAD

**Issue by Mrkbingham** [tableau/embedding-api-v3-guide#8]
Will the ability to create new data-driven alerts be exposed through the API when the toolbar is not enabled?

**Comment by benyoung-iw** [comment]
^+1 to @Mrkbingham's question. It would be fantastic to have these functionalities available in an embedded experience without having to surface the toolbar.

**Comment by Kovner** [comment]
Great question: We have a feature (or really a goal that is many features) of having 'full toolbar support', by which we mean anything you can do in the toolbar, you should be able to do via API. Another example is exporting images, pdfs, etc. You can currently launch those dialogs, but you can choose options or execute them via API and we hope to make that all available in addition to things like DDA, etc.

However, we consider that a separate milestone from the Embedding API v3. We intend to start tackling the toolbar support items shortly after releasing the Embedding API v3.

**Comment by bcantoni** [comment]
We don't anticipate adding this in the future, so I'll close it out.
